---
# This playbook causes OpenSCAP rule `xccdf_org.ssgproject.content_rule_sshd_set_idle_timeout` to fail
- hosts: tag_Service_testing_machine
  become: true
  vars:
    sshd_idle_timeout_value: !!str 0
  tasks:
    - name: 1.0 | Set SSH Idle Timeout Interval | Deduplicate values from `/etc/ssh/sshd_config`
      lineinfile:
        path: /etc/ssh/sshd_config
        create: false
        regexp: (?i)^\s*ClientAliveInterval\s+
        state: absent
      tags:
        - sshd_set_idle_timeout
        - medium_severity
        - restrict_strategy
        - low_complexity
        - low_disruption
        - no_reboot_needed
        - CCE-80906-1
        - NIST-800-53-CM-6(a)
        - NIST-800-53-AC-17(a)
        - NIST-800-53-AC-2(5)
        - NIST-800-53-AC-12
        - NIST-800-53-AC-17(a)
        - NIST-800-53-SC-10
        - NIST-800-53-CM-6(a)
        - NIST-800-171-3.1.11
        - PCI-DSS-Req-8.1.8
        - CJIS-5.5.6

    - name: 2.0 | Set SSH Idle Timeout Interval | Insert incorrect line to `/etc/ssh/sshd_config`
      lineinfile:
        path: /etc/ssh/sshd_config
        create: true
        line: ClientAliveInterval {{ sshd_idle_timeout_value }}
        state: present
        insertbefore: ^[#\s]*Match
        validate: /usr/sbin/sshd -t -f %s
      tags:
        - incorrect
        - sshd_set_idle_timeout
        - medium_severity
        - restrict_strategy
        - low_complexity
        - low_disruption
        - no_reboot_needed
        - CCE-80906-1
        - NIST-800-53-CM-6(a)
        - NIST-800-53-AC-17(a)
        - NIST-800-53-AC-2(5)
        - NIST-800-53-AC-12
        - NIST-800-53-AC-17(a)
        - NIST-800-53-SC-10
        - NIST-800-53-CM-6(a)
        - NIST-800-171-3.1.11
        - PCI-DSS-Req-8.1.8
        - CJIS-5.5.6
